import { expect, test, type Page } from '@playwright/test';
import { FROZEN_NOW } from '../../playwright.config';
import { DEMO, expectSurface } from './support';

/**
 * The auth surface, and the flow that turns a stranger into a diary.
 *
 * Signed out on purpose, which is why these live in the `public` project: an
 * operator session on `/login` is a redirect straight back out, so a spec
 * carrying one can never see the form it is about.
 *
 * **375 is the width that matters here.** The rule `GuestLayout` is built to is
 * that the page is never a centred card at any width, and 375 is where a
 * two-column layout usually collapses back into one. Login is snapshotted at
 * all three because it is the screen everyone sees every day; the rest are
 * snapshotted at 375 only, for the same reason `customers-375` is — one width
 * per screen, at the width where the layout actually has to decide something.
 */

/** Wait for the fonts the design depends on, or the first run snapshots Arial. */
async function settled(page: Page): Promise<void> {
    await page.evaluate(() => document.fonts.ready);
    await page.waitForTimeout(250);
}

async function at(page: Page, width: number, height = 900): Promise<void> {
    await page.clock.setFixedTime(new Date(FROZEN_NOW));
    await page.setViewportSize({ width, height });
}

test.describe('signing in', () => {
    for (const width of [375, 768, 1280] as const) {
        test(`login at ${width}`, async ({ page }) => {
            await at(page, width, width === 375 ? 900 : 1000);
            await page.goto('/login');
            await expect(page.getByRole('heading', { name: 'Sign in' })).toBeVisible();
            await settled(page);

            await expect(page).toHaveScreenshot(`login-${width}.png`, { fullPage: true });
        });
    }

    /*
     * The rule, asserted rather than left to the picture. A snapshot can tell
     * you the page changed; it cannot tell you it stopped being a page and went
     * back to being a box.
     */
    test('is a page rather than a centred card, at every width', async ({ page }) => {
        for (const width of [375, 768, 1280]) {
            await at(page, width);
            await page.goto('/login');
            await expect(page.getByRole('heading', { name: 'Sign in' })).toBeVisible();

            // The heading sits against the page's own left edge, not centred in
            // the viewport. A centred card puts it near the middle.
            const box = await page.getByRole('heading', { name: 'Sign in' }).boundingBox();
            expect(box, `no heading at ${width}`).not.toBeNull();
            expect(box!.x, `heading is centred at ${width}`).toBeLessThan(width / 3);

            // And nothing scrolls sideways.
            expect(
                await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),
                `page scrolls sideways at ${width}`,
            ).toBe(true);

            /*
             * The two surfaces, asserted rather than photographed.
             *
             * A screenshot cannot see this. `--paper` and `--paper-sunk` are a
             * YIQ delta of 40.8 apart and `--paper` and `--white` are 8.3 —
             * both under the per-pixel threshold that still tolerates font
             * rasterisation elsewhere. The quiet column disappearing at 768 is
             * exactly the regression that slipped through, so it is checked
             * here in a way that does not depend on pixels at all.
             */
            // Inertia mounts into `#app`, which is transparent; the layout's own
            // root is the element that carries the surface.
            await expectSurface(page.locator('#app > div').first(), 'paper', 'the auth page');

            const panel = page.locator('aside');

            if (width >= 1024) {
                await expect(panel).toBeVisible();
                await expectSurface(panel, 'paperSunk', 'the auth page’s quiet column');
            } else {
                await expect(panel).toBeHidden();
            }
        }
    });

    /**
     * The focus ring is the product's, not the plugin's.
     *
     * `@tailwindcss/forms` styles `[type='text']:focus` with
     * `border-color: #2563eb` — Tailwind blue-600, in a product with no blue in
     * its palette — at a specificity above `base.css`'s `:focus-visible` rule.
     * Every focused field in the app wore it, and `npm run check` reported the
     * design system clean throughout, because the colour is generated by a
     * plugin at build time and never appears in anything we author.
     *
     * It was found by sampling a pixel off a screenshot, which is not a process.
     * Asserted here instead, in a real browser on a real focused control, which
     * is the only place the question has a true answer — the plugin's
     * declaration is still in the built stylesheet either way, it simply loses.
     */
    test('the focus ring is the accent, not the form plugin\'s blue', async ({ page }) => {
        await at(page, 1280, 1000);
        await page.goto('/login');

        const email = page.locator('input[type="email"]');
        await email.focus();

        const style = await email.evaluate((el) => {
            const computed = getComputedStyle(el);

            return { border: computed.borderTopColor, shadow: computed.boxShadow };
        });

        // --accent, #A85729.
        expect(style.shadow).toContain('168, 87, 41');
        // And not blue-600 on the border, which is what the plugin wanted.
        expect(style.border).not.toContain('37, 99, 235');
    });

    /*
     * A failed sign-in is a designed state, and the thing most often shipped
     * unconsidered. It has to be findable, and it has to say what happened
     * rather than sit under the email field looking like a format complaint.
     */
    test('says what happened when the details are wrong', async ({ page }) => {
        await at(page, 375);
        await page.goto('/login');

        await page.locator('input[type="email"]').fill('nobody@paw.test');
        await page.locator('input[type="password"]').fill('not-the-password');
        await page.getByRole('button', { name: 'Sign in' }).click();

        const alert = page.getByRole('alert').filter({ hasText: /credentials|match/i }).first();
        await expect(alert).toBeVisible();
        await settled(page);

        await expect(page).toHaveScreenshot('login-error-375.png', { fullPage: true });
    });

    /*
     * The host-mismatch footgun. The e2e server's APP_URL is 127.0.0.1 (see
     * playwright.config.ts). Opening the form on localhost used to post to
     * 127.0.0.1, drop the session, and sit there. Relative same-surface URLs
     * plus a host-local login redirect are the fix; this is the proof they
     * hold without editing .env.
     */
    test('signs in from localhost even when APP_URL is 127.0.0.1', async ({ page, baseURL }) => {
        await at(page, 1280);
        const login = (baseURL ?? 'http://127.0.0.1:8129').replace('127.0.0.1', 'localhost') + '/login';

        await page.goto(login);
        await page.locator('input[type="email"]').fill(DEMO.ownerEmail);
        await page.locator('input[type="password"]').fill(DEMO.ownerPassword);
        await page.getByRole('button', { name: 'Sign in' }).click();

        await expect(page).toHaveURL(/\/diary/);
        expect(new URL(page.url()).hostname).toBe('localhost');
    });
});

/**
 * Setting up a business, end to end, on a phone.
 *
 * Five screens, and the point of the spec is that the progress is legible on
 * every one of them at the width where there is no room for a rail. Each step
 * is snapshotted, so none of them can regress silently.
 *
 * It registers a real tenant. That is safe: the e2e database is dropped and
 * rebuilt on every run, and this tenant is not `paw` — nothing else in the
 * suite looks at it.
 *
 * The email carries a timestamp because `users.email` is unique and the first
 * version of this did not: `npm run test:e2e` reseeds, so it passed, and
 * running `playwright test` twice by hand against the same database failed on
 * the second go with a validation error that looked like a broken form. The
 * address is never on a snapshot — step one is captured before anything is
 * typed — so a value that changes every run cannot move a baseline.
 */
const SIGNUP_EMAIL = `maya+${Date.now()}@willowstreet.example`;
test.describe('setting up a business at 375', () => {
    test('walks all five steps with the progress legible on each', async ({ page }) => {
        await at(page, 375, 1400);

        /* -- 1. Your account ------------------------------------------------ */
        await page.goto('/register');
        await expect(page.getByRole('heading', { name: 'Set up your business' })).toBeVisible();
        await settled(page);
        await expect(page).toHaveScreenshot('setup-1-account-375.png', { fullPage: true });

        // The compact progress is the 375 shape of the rail, and it is the only
        // thing telling this person how long this is going to take.
        await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuemax', '5');
        await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '1');

        await page.getByLabel('Business name').fill('Willow Street Grooming');
        /*
         * The trade, and it is required — `RegisterRequest` wants a key that
         * exists in `verticals`, and the control carries `required` so the
         * browser will not even post without it. This walk-through predates the
         * field: it filled every other input, clicked Create the account, and
         * the form silently refused to submit, so the spec sat on step one
         * waiting for step two's heading until it timed out. A missing select
         * fails as a timeout somewhere else, which is the worst shape a test
         * failure can take.
         */
        await page.getByLabel('What kind of business?').selectOption('groomer');
        await page.getByLabel('Your name').fill('Maya Chen');
        await page.getByLabel('Email').fill(SIGNUP_EMAIL);
        await page.getByLabel('Password', { exact: false }).first().fill('correct-horse-battery');
        await page.getByLabel('Confirm password').fill('correct-horse-battery');
        await page.getByRole('button', { name: 'Create the account' }).click();

        /* -- 2. Business details -------------------------------------------- */
        await expect(page.getByRole('heading', { name: 'Where you are' })).toBeVisible();
        await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '2');
        await settled(page);
        await expect(page).toHaveScreenshot('setup-2-business-375.png', { fullPage: true });

        await page.getByLabel('Phone').fill('020 7946 0123');
        await page.getByLabel('Address', { exact: true }).fill('12 Willow Street');
        await page.getByLabel('Town or city').fill('London');
        await page.getByLabel('Postcode').fill('E8 3AA');
        await page.getByRole('button', { name: 'Save and continue' }).click();

        /* -- 3. Services ----------------------------------------------------- */
        await expect(page.getByRole('heading', { name: 'What you do' })).toBeVisible();
        await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '3');
        await settled(page);
        await expect(page).toHaveScreenshot('setup-3-services-375.png', { fullPage: true });

        await page.getByRole('button', { name: 'Save and continue' }).click();

        /* -- 4. People ------------------------------------------------------- */
        await expect(page.getByRole('heading', { name: 'Who does it' })).toBeVisible();
        await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '4');
        // A salon of one is a stated answer, not an empty pair of fields.
        await expect(page.getByText('Just you, for now')).toBeVisible();
        await settled(page);
        await expect(page).toHaveScreenshot('setup-4-people-375.png', { fullPage: true });

        await page.getByRole('button', { name: 'Save and continue' }).click();

        /* -- 5. Opening hours ------------------------------------------------ */
        await expect(page.getByRole('heading', { name: 'When you are open' })).toBeVisible();
        await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '5');
        await settled(page);
        await expect(page).toHaveScreenshot('setup-5-hours-375.png', { fullPage: true });

        /* -- Back does not lose anything ------------------------------------- */
        await page.getByRole('link', { name: /^Back to/ }).click();
        await expect(page.getByRole('heading', { name: 'Who does it' })).toBeVisible();
        await page.getByRole('link', { name: /^Back to/ }).click();
        await expect(page.getByRole('heading', { name: 'What you do' })).toBeVisible();
        // The services typed two steps ago are still there.
        await expect(page.getByLabel('Name').first()).not.toHaveValue('');
    });
});
